#!/bin/bash
if [ -z "$1" ]; then
	printf "USAGE: %s [tests 1-8]\n" "$0" > /dev/stderr
	false
elif [ "$1" == "1" ]; then
	pushd 2\ -\ Data\ Types\ and\ Variables > /dev/null
	pushd tdd/test > /dev/null
	cp ../camper/camper_age_input.py . > /dev/null
	printf "1: camper_age_input.py, 2: test_functions.py\n"
	./test_functions.py
	rm -f camper_age_input.py > /dev/null
	popd > /dev/null
	popd > /dev/null
	true
elif [ "$1" == "2" ]; then
	pushd 3\ -\ Strings,\ Basic\ IO,\ Operators > /dev/null
	pushd io/test > /dev/null
	cp ../average_scores/average_scores.py . > /dev/null
	printf "1: average_scores.py, 2: test.py\n"
	./test.py
	rm -f average_scores.py > /dev/null
	popd > /dev/null
	popd > /dev/null
	true
elif [ "$1" == "3" ]; then
	pushd 4\ -\ Conditional\ Operators > /dev/null
	pushd Input\ Validation/test > /dev/null
	cp ../input_validation/validation_with_if.py . > /dev/null
	printf "1: validation_with_if.py, 2: test_validation_with_if.py\n"
	./test_validation_with_if.py
	rm -f validation_with_if.py > /dev/null
	popd > /dev/null
	popd > /dev/null
	true
elif [ "$1" == "4" ]; then
	pushd 4\ -\ Conditional\ Operators > /dev/null
	pushd Nested\ If/test > /dev/null
	cp ../store/coupon_calculations.py . > /dev/null
	printf "1: coupon_calculations.py, 2: test_coupon_calculations.py\n"
	./test_coupon_calculations.py
	rm -f coupon_calculations.py > /dev/null
	popd > /dev/null
	popd > /dev/null
	true
elif [ "$1" == "5" ]; then
	pushd 4\ -\ Conditional\ Operators > /dev/null
	pushd Try/test > /dev/null
	cp ../validation_try/validation_with_try.py . > /dev/null
	printf "1: validation_with_try.py, 2: test_validation_with_try.py\n"
	./test_validation_with_try.py
	rm -f validation_with_try > /dev/null
	popd > /dev/null
	popd > /dev/null
	true
elif [ "$1" == "6" ]; then
	pushd 5\ -\ Loops > /dev/null
	pushd input/test > /dev/null
	cp ../input_loops/average_input_scores.py . > /dev/null
	printf "1: average_input_scores.py, 2: test_loop.py\n"
	./test_loop.py
	rm -f average_input_scores.py > /dev/null
	popd > /dev/null
	popd > /dev/null
	true
elif [ "$1" == "7" ]; then
	pushd 6\ -\ Functions > /dev/null
	pushd Module6/test_functions > /dev/null
	cp ../more_functions/string_functions.py . > /dev/null
	printf "1: string_functions.py, 2: test_string_functions.py\n"
	./test_string_functions.py
	rm -f string_functions.py > /dev/null
	popd > /dev/null
	popd > /dev/null
	true
elif [ "$1" == "8" ]; then
	pushd 6\ -\ Functions > /dev/null
	pushd Inner\ Functions/test > /dev/null
	cp ../inner_functions/inner_functions_assignment.py . > /dev/null
	printf "1: inner_functions_assignment.py, 2: test_inner_functions.py\n"
	./test_inner_functions.py
	rm -f inner_functions_assignment.py > /dev/null
	popd > /dev/null
	popd > /dev/null
	true
elif [ "$1" == "9" ]; then
	pushd 7\ -\ Collections > /dev/null
	pushd Module7/test_collections > /dev/null
	cp ../fun_with_collections/basic_list.py . > /dev/null
	printf "1: basic_list.py, 2: test_basic_list.py\n"
	./test_basic_list.py
	rm -f basic_list.py > /dev/null
	popd > /dev/null
	popd > /dev/null
	true
elif [ "$1" == "10" ]; then
	pushd 8\ -\ Sets\ and\ Dictionaries > /dev/null
	pushd Module8/test > /dev/null
	cp ../more_fun_with_collections/set_membership.py . > /dev/null
	printf "1: set_membership.py, 2: test_set_membership.py\n"
	./test_set_membership.py
	rm -f set_membership.py > /dev/null
	popd > /dev/null
	popd > /dev/null
	true
fi

